services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: complaint-portal-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: complaint_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migration.sql:/docker-entrypoint-initdb.d/migration.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - complaint-portal-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: complaint-portal-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD:-password123}@postgres:5432/complaint_portal
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      JWT_EXPIRES_IN: 24h
      PORT: 3001
      NODE_ENV: ${NODE_ENV:-production}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - complaint-portal-network

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: complaint-portal-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      REACT_APP_API_URL: ${API_URL:-http://localhost:3001}
    depends_on:
      - backend
    networks:
      - complaint-portal-network

volumes:
  postgres_data:
    name: complaint-portal-db-data

networks:
  complaint-portal-network:
    driver: bridge
    name: complaint-portal-network